<a href="https://colab.research.google.com/github/vishnudatt18/PYTHON-ASSIGNMENT/blob/main/numpy_assign.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [145]:
# 1.How do you import the NumPy library using an alias?
import numpy as np

In [146]:
# 2.How do you check the version and configuration of NumPy?
print(np.__version__)
print(np.show_config())

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

In [147]:
# 3.How do you create a vector filled with zeros of size 10?
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [148]:
# 5.How do you create a zero vector of size 10 with the fifth element as 1?
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [149]:
# 6.How do you create a vector with values from 10 to 49?
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [150]:
# 7.How do you reverse a vector?
arr = np.arange(10)
arr = arr[::-1]
print(arr)

[9 8 7 6 5 4 3 2 1 0]


In [151]:
# 8.How do you create a 3x3 matrix with values from 0 to 8?
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [152]:
# 9.How do you find indices of non-zero elements in an array?
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4]),)


In [153]:
# 10.How do you create a 3x3 identity matrix?
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [154]:
# 11.How do you generate a 3x3x3 array with random values?
arr3 = np.random.rand(3, 3, 3)
print(arr3)

[[[0.45916618 0.27736608 0.65888032]
  [0.34758739 0.97222948 0.20602966]
  [0.2437538  0.13208744 0.33537977]]

 [[0.18478055 0.43986541 0.44611872]
  [0.86597837 0.08060087 0.63906742]
  [0.70559079 0.52882365 0.71863707]]

 [[0.24565777 0.47167503 0.11202321]
  [0.63566374 0.82323269 0.67689581]
  [0.62632867 0.18445811 0.22947151]]]


In [155]:
# 12.How do you find the min and max values in a 10x10 random matrix?
arr = np.random.rand(10, 10)
min_val = np.min(arr)
max_val = np.max(arr)

print("Min value:", min_val)
print("Max value:", max_val)

Min value: 0.0047505310934785605
Max value: 0.9955522531663611


In [156]:
# 13.How do you calculate the mean of a random vector of size 30?
arr = np.random.rand(30)
mean_val = np.mean(arr)
print("Mean value:", mean_val)

Mean value: 0.5527545911368995


In [157]:
# 14.How do you create a 2D array with 1s on the border and 0s inside?
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [158]:
# 15.What is the result of operations like 0 * np.nan, np.nan == np.nan, etc.?
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)


nan
False
False
nan


In [159]:
# 16.How do you create a matrix with values below the diagonal?
arr = np.diag(np.arange(1, 5), k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [160]:
# 17.How do you create a checkerboard pattern in an 8x8 matrix?

arr = np.zeros((8, 8), dtype=int)
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [161]:
# 18.How do you find the index of a flat element in a 3D shape?

arr = np.arange(64).reshape((4, 4, 4))
index = np.unravel_index(10, arr.shape)
print(index)

(np.int64(0), np.int64(2), np.int64(2))


In [162]:
# 19.How do you create a checkerboard pattern using NumPy's tile function?

arr = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [163]:
# 20.How do you normalize a matrix (values between 0 and 1)?

arr = np.random.rand(5, 5)
arr_normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print(arr_normalized)

[[0.21899378 0.20614085 0.25353669 0.76191501 0.18308688]
 [0.40762705 0.54983697 0.50472274 0.56924957 0.42938315]
 [0.81394224 0.09897657 0.7813715  0.70393542 0.        ]
 [0.44506496 0.76094994 0.2127178  0.90856222 0.60792408]
 [0.19699892 0.63039068 0.08647287 0.99649592 1.        ]]


In [164]:
# 21.How do you define a custom data type for storing color (RGBA)?

color = np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [165]:
# 22.How do you perform a matrix multiplication between two matrices?

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
print(result)

[[19 22]
 [43 50]]


In [166]:
# 23.How do you negate values between two given numbers in a vector?

arr = np.arange(10)
arr[(arr > 3) & (arr < 8)] *= -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


In [167]:
# 24.What is the output of sum(range(5), -1) vs np.sum(range(5), -1)?

print(sum(range(5), -1))
print(np.sum(list(range(5)), axis=-1))

9
10


In [168]:
# 25.Which NumPy vector operations are legal or illegal?


In [169]:
# 26.What happens when you divide integers or floats by zero in NumPy?
# Integer division by zero raises an error. Float division by zero results in inf or -inf, or nan.
print(np.array([1, 0]) / np.array([0, 0])) # Example with float division
# print(np.array([1, 0]) // np.array([0, 0])) # Example with integer division (will raise error)

[inf nan]


/tmp/ipython-input-4294434204.py:3: RuntimeWarning: divide by zero encountered in divide
  print(np.array([1, 0]) / np.array([0, 0])) # Example with float division
/tmp/ipython-input-4294434204.py:3: RuntimeWarning: invalid value encountered in divide
  print(np.array([1, 0]) / np.array([0, 0])) # Example with float division


In [170]:
# 27.How do you round a float array away from zero?
arr = np.array([-1.7, -1.5, -1.3, 1.3, 1.5, 1.7])
print(np.copysign(np.ceil(np.abs(arr)), arr))

[-2. -2. -2.  2.  2.  2.]


In [171]:
# 28.How do you extract the integer part of a float using multiple methods?
arr = np.array([1.23, 2.89, -3.45])
print(arr.astype(int))
print(np.trunc(arr))
print(np.floor(arr))
print(np.ceil(arr) - (arr < 0))

[ 1  2 -3]
[ 1.  2. -3.]
[ 1.  2. -4.]
[ 2.  3. -4.]


In [172]:
# 29.How do you create a 5x5 matrix with row values ranging from 0 to 4?
arr = np.zeros((5, 5))
arr += np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [173]:
# 30.How do you use a generator to create a NumPy array?
def generate():
  for i in range(10):
    yield i
arr = np.fromiter(generate(), dtype=float, count=-1)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [174]:
# 31.How do you create an array with evenly spaced values between 0 and 1 (excluded)?
arr = np.linspace(0, 1, 11, endpoint=False)[1:]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [175]:
# 32.How do you sort a random array?
arr = np.random.rand(10)
arr.sort()
print(arr)

[0.39529719 0.51524917 0.5417475  0.56963047 0.68384524 0.70818107
 0.7219431  0.74630845 0.81238198 0.95681832]


In [176]:
# 33.How do you sum an array faster than using np.sum?
arr = np.arange(1000)
# Using the built-in sum is often faster for small arrays or lists
# For larger NumPy arrays, np.sum is highly optimized and generally faster
%timeit sum(arr)
%timeit np.sum(arr)

89.2 µs ± 1.52 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
4.48 µs ± 1.25 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [177]:
# 34.How do you check if two arrays are equal?
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
arr3 = np.array([1, 2, 4])
print(np.array_equal(arr1, arr2))
print(np.array_equal(arr1, arr3))

True
False


In [178]:
# 35.How do you make a NumPy array read-only?
arr = np.arange(10)
arr.flags.writeable = False
# arr[0] = 11 # This would raise an error
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [179]:
# 36.How do you convert Cartesian coordinates to polar coordinates?
z = np.array([1 + 1j, 2 + 3j, -1 - 2j])
rho = np.abs(z)
phi = np.angle(z)
print("Rho:", rho)
print("Phi:", phi)

Rho: [1.41421356 3.60555128 2.23606798]
Phi: [ 0.78539816  0.98279372 -2.03444394]


In [180]:
# 37.How do you replace the maximum value in an array with zero?
arr = np.random.rand(5)
arr[arr.argmax()] = 0
print(arr)

[0.44327494 0.48369951 0.44184912 0.         0.29318837]


In [181]:
# 38.How do you create a structured array for (x, y) coordinate pairs?
Z = np.zeros(10, [ ('x', float), ('y', float)])
print(Z)

[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
 (0., 0.) (0., 0.)]


In [182]:
# 39.How do you create a Cauchy matrix using two arrays?
x = np.arange(8)
y = x + 0.5
C = 1.0 / (x[:, np.newaxis] - y)
print(C)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]


In [183]:
# 40.How do you find the range of values for each NumPy scalar type?
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min, np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min, np.finfo(dtype).max)

-128 127
-2147483648 2147483647
-9223372036854775808 9223372036854775807
-3.4028235e+38 3.4028235e+38
-1.7976931348623157e+308 1.7976931348623157e+308


In [184]:
# 41.How do you display all values in a large array?
# By default, NumPy truncates the display of large arrays.
# You can change the print options to display all values:
# np.set_printoptions(threshold=np.inf)
# print(np.arange(1000))
# To reset to default:
# np.set_printoptions(threshold=1000)
print("NumPy's default behavior for large arrays is to truncate the display.")
print("Use np.set_printoptions(threshold=np.inf) to display all values.")

NumPy's default behavior for large arrays is to truncate the display.
Use np.set_printoptions(threshold=np.inf) to display all values.


In [185]:
# 42.How do you find the closest value to a given scalar in an array?
Z = np.random.uniform(0,10,10)
z = 5
index = (np.abs(Z - z)).argmin()
print(Z[index])

5.501163472082142


In [186]:
# 43.How do you create a structured array with position and color fields?
Z = np.zeros(10, [ ('position', [ ('x', float, 1), ('y', float, 1)]),
                   ('color',    [ ('r', float, 1), ('g', float, 1), ('b', float, 1)])])
print(Z)

[(([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))]


In [187]:
# 44.How do you compute pairwise distances between coordinates?
Z = np.random.rand(10, 2)
X, Y = np.meshgrid(np.arange(10), np.arange(10))
D = np.sqrt((Z[X, 0] - Z[Y, 0])**2 + (Z[X, 1] - Z[Y, 1])**2)
print(D)

[[0.         0.48826547 0.13805152 0.29334492 0.5073277  0.44745032
  0.87692681 0.62160586 0.4986956  0.23349304]
 [0.48826547 0.         0.6218921  0.24236957 0.66844962 0.37158207
  0.41360851 0.27312342 0.15558176 0.37790437]
 [0.13805152 0.6218921  0.         0.41059059 0.57376362 0.57111232
  1.01468107 0.73082317 0.61737598 0.31706892]
 [0.29334492 0.24236957 0.41059059 0.         0.65331503 0.43586804
  0.65597693 0.32904494 0.20694534 0.13560527]
 [0.5073277  0.66844962 0.57376362 0.65331503 0.         0.31430814
  0.86613876 0.92325626 0.7842045  0.68843612]
 [0.44745032 0.37158207 0.57111232 0.43586804 0.31430814 0.
  0.56534645 0.64060221 0.50771681 0.52371926]
 [0.87692681 0.41360851 1.01468107 0.65597693 0.86613876 0.56534645
  0.         0.53787572 0.51397471 0.79150187]
 [0.62160586 0.27312342 0.73082317 0.32904494 0.92325626 0.64060221
  0.53787572 0.         0.13993482 0.41880432]
 [0.4986956  0.15558176 0.61737598 0.20694534 0.7842045  0.50771681
  0.51397471 0.13993

In [188]:
# 45.How do you cast a float array to integer type in place?
arr = np.random.uniform(0, 10, 10)
arr = arr.astype(np.int32, copy=False)
print(arr)

[2 6 1 5 8 9 3 3 0 9]


In [189]:
# 46.How do you read data from a file with missing values?
# Assuming a file named 'data.txt' with missing values represented by 'NA' or similar
# data = np.genfromtxt('data.txt', delimiter=',', missing_values='NA')
print("This requires a file. Assuming a file 'data.txt' with missing values.")
print("Use np.genfromtxt('data.txt', delimiter=',', missing_values='NA')")

This requires a file. Assuming a file 'data.txt' with missing values.
Use np.genfromtxt('data.txt', delimiter=',', missing_values='NA')


In [190]:
# 47.How do you iterate through all elements in a NumPy array with indices?
arr = np.arange(12).reshape(3, 4)
for index, value in np.ndenumerate(arr):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11


In [191]:
# 48.How do you create a 2D Gaussian-like array?
x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(x*x + y*y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D - mu)**2 / (2.0 * sigma**2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [192]:
# 49.How do you randomly place a specific number of elements in a 2D array?
n = 10
arr = np.zeros((10, 10))
i = np.random.randint(0, 10, n)
j = np.random.randint(0, 10, n)
arr[i, j] = 1
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [193]:
# 50.How do you subtract the row mean from a matrix?
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.04526527 -0.16936682  0.32746288 -0.22927985 -0.32926458  0.56230573
  -0.07205636 -0.17190824 -0.34052558  0.46789809]
 [-0.30026921 -0.27556244  0.54159173 -0.38434197  0.40326424 -0.05720497
  -0.29291666  0.37947204  0.18786307 -0.20189582]
 [ 0.35079996  0.05852476  0.16583249 -0.22896092  0.09415343  0.12859272
  -0.31308988  0.20759608  0.06559516 -0.52904381]
 [ 0.34102077 -0.35416175 -0.037784   -0.51395589  0.42952861  0.07215484
   0.42604409 -0.21438441  0.36492454 -0.5133868 ]
 [-0.07098804 -0.14644892 -0.11251857  0.56200556 -0.03483975 -0.14908556
  -0.10596005 -0.0660639   0.21772358 -0.09382434]]


In [194]:
# 51.How do you sort a 2D array based on the values of one column?
arr = np.random.rand(5, 3)
arr = arr[arr[:, 1].argsort()]
print(arr)

[[0.92655117 0.0956227  0.40014633]
 [0.75578616 0.17988303 0.04221449]
 [0.51278038 0.35069882 0.34395908]
 [0.17200738 0.5127699  0.135652  ]
 [0.66372957 0.77904534 0.69917833]]


In [195]:
# 52.How do you check if a 2D array contains any null (zero-only) columns?
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


In [196]:
# 53.How do you find the nearest value to a given number in a NumPy array?
Z = np.random.uniform(0,10,10)
z = 5
index = (np.abs(Z - z)).argmin()
print(Z[index])

6.1279793760632115


In [197]:
# 54.How do you create a NumPy subclass with custom attributes?
# This is a more advanced topic and requires defining a custom class.
# Example structure:
# class MyArray(np.ndarray):
#     def __new__(cls, input_array, custom_attribute):
#         obj = np.asarray(input_array).view(cls)
#         obj.custom_attribute = custom_attribute
#         return obj
#     def __array_finalize__(self, obj):
#         if obj is None: return
#         self.custom_attribute = getattr(obj, 'custom_attribute', None)
print("Creating a NumPy subclass requires defining a custom class.")
print("See NumPy documentation for details on subclassing ndarray.")

Creating a NumPy subclass requires defining a custom class.
See NumPy documentation for details on subclassing ndarray.


In [198]:
# 55.How do you increment elements in an array using an index array with repeats?
arr = np.ones(10)
i = np.array([0, 1, 2, 3, 4, 4, 6, 7, 8, 9])
np.add.at(arr, i, 1)
print(arr)

[2. 2. 2. 2. 3. 1. 2. 2. 2. 2.]


In [199]:
# 56.How do you accumulate values into an array based on indices?
arr = np.zeros(10)
i = np.array([0, 1, 2, 3, 4, 4, 6, 7, 8, 9])
v = np.arange(10)
np.add.at(arr, i, v)
print(arr)

[0. 1. 2. 3. 9. 0. 6. 7. 8. 9.]


In [200]:
# 57.How do you count unique colors in a 3D image array?
# Assuming a 3D array representing an image with shape (height, width, channels)
# image = np.random.randint(0, 256, (10, 10, 3), dtype=np.uint8)
# reshape the image to be a 2D array of pixels
# pixels = image.reshape(-1, 3)
# Use np.unique to find unique rows (colors)
# unique_colors = np.unique(pixels, axis=0)
# print(len(unique_colors))
print("Counting unique colors requires a 3D image array.")
print("Reshape the array to 2D and use np.unique with axis=0.")

Counting unique colors requires a 3D image array.
Reshape the array to 2D and use np.unique with axis=0.


In [201]:
# 58.How do you compute the sum across the last two axes of a 4D array?
arr = np.random.rand(2, 3, 4, 5)
sum_last_two_axes = arr.sum(axis=(-2, -1))
print(sum_last_two_axes)

[[ 9.07528663  9.39890998  9.91663744]
 [10.40080213 11.25853389  8.7874203 ]]


In [202]:
# 59.How do you calculate means of grouped values in an array?
# This is typically done with libraries like pandas, or by sorting and using split.
# Example with pandas:
# import pandas as pd
# df = pd.DataFrame({'group': ['A', 'A', 'B', 'B', 'A'], 'value': [10, 15, 12, 18, 20]})
# means = df.groupby('group')['value'].mean()
# print(means)
print("Calculating means of grouped values is often done with pandas or by sorting and splitting.")
print("See pandas documentation for groupby.")

Calculating means of grouped values is often done with pandas or by sorting and splitting.
See pandas documentation for groupby.


In [203]:
# 60.How do you efficiently get the diagonal of a matrix dot product?
A = np.random.rand(5, 5)
B = np.random.rand(5, 5)
# The diagonal of the dot product (A @ B) is the sum of the element-wise product of corresponding rows of A and columns of B.
# This can be calculated efficiently using np.einsum or broadcasting and sum.
diagonal = np.einsum('ij,ji->i', A, B)
print(diagonal)

[2.1314721  1.51823888 1.54883395 1.05380378 1.85483031]


In [204]:
# 61.How do you interleave a vector with a fixed number of zeros?
arr = np.arange(10)
n = 3 # number of zeros to interleave
zeros = np.zeros(len(arr) + (len(arr)-1)*n)
zeros[::n+1] = arr
print(zeros)

[0. 0. 0. 0. 1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0.
 6. 0. 0. 0. 7. 0. 0. 0. 8. 0. 0. 0. 9.]


In [205]:
# 62.How do you multiply a (5,5,3) array with a (5,5) array element-wise?
A = np.random.rand(5, 5, 3)
B = np.random.rand(5, 5)
result = A * B[:, :, np.newaxis]
print(result)

[[[6.87589058e-01 1.91418903e-01 2.19216298e-01]
  [5.36155971e-03 7.37384274e-02 6.78017575e-02]
  [3.13759548e-03 1.15387713e-01 8.32516602e-02]
  [1.95284674e-01 1.28364846e-01 6.71302755e-02]
  [6.10522403e-02 2.94363543e-02 2.39350879e-03]]

 [[1.02902620e-01 1.23379290e-01 2.33059214e-01]
  [6.53277486e-01 1.38769636e-01 1.73683482e-01]
  [8.15520754e-04 3.21077540e-04 5.37856526e-04]
  [9.97417079e-02 3.14679986e-01 4.11483408e-01]
  [6.61637013e-02 2.99211263e-02 8.39946729e-03]]

 [[5.13206406e-01 6.92849980e-01 3.96119753e-01]
  [6.32692828e-02 3.17529913e-01 1.00333830e-01]
  [1.43420899e-02 2.38213957e-02 1.92079475e-02]
  [1.50072534e-03 9.00016911e-02 5.99221460e-02]
  [2.41184696e-02 5.73308929e-01 5.07732966e-01]]

 [[1.78822226e-01 3.10702442e-01 4.62458105e-01]
  [5.81413588e-01 2.99005517e-01 7.59430482e-01]
  [3.17734833e-02 4.00107366e-01 1.71195364e-01]
  [5.91153832e-01 4.14541432e-01 4.38088854e-01]
  [1.42483216e-01 3.93444475e-01 1.38830469e-01]]

 [[1.8344077

In [206]:
# 63.How do you swap two rows in a matrix?
arr = np.arange(25).reshape(5, 5)
arr[[0, 1]] = arr[[1, 0]]
print(arr)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [207]:
# 64.How do you extract unique line segments from triangle definitions?
import numpy as np
# Assuming a set of triangles defined by indices of points in an array
points = np.random.rand(10, 2)
triangles = np.random.randint(0, 10, (5, 3))

# Extract the segments (edges) from the triangles
# Each triangle has 3 edges: (p1, p2), (p2, p3), (p3, p1)
segments = np.concatenate([points[triangles[:, [0, 1]]],
                           points[triangles[:, [1, 2]]],
                           points[triangles[:, [2, 0]]]], axis=0)

# Sort the points within each segment to treat (p1, p2) and (p2, p1) as the same segment
segments = np.sort(segments, axis=1)

# Find unique segments
unique_segments = np.unique(segments, axis=0)
print(unique_segments)

[[[0.14556403 0.33625879]
  [0.4771212  0.46112595]]

 [[0.14556403 0.45049635]
  [0.79919427 0.46112595]]

 [[0.14556403 0.46112595]
  [0.14556403 0.46112595]]

 [[0.14556403 0.46112595]
  [0.84986626 0.83644284]]

 [[0.23293194 0.27401329]
  [0.4771212  0.33625879]]

 [[0.23293194 0.27401329]
  [0.80785092 0.36724958]]

 [[0.35163201 0.05542655]
  [0.4771212  0.33625879]]

 [[0.35163201 0.05542655]
  [0.80785092 0.36724958]]

 [[0.4771212  0.33625879]
  [0.80785092 0.36724958]]

 [[0.79919427 0.36724958]
  [0.80785092 0.45049635]]

 [[0.79919427 0.45049635]
  [0.84986626 0.83644284]]

 [[0.80785092 0.36724958]
  [0.84986626 0.83644284]]]


In [208]:
# 65.How do you recreate an array from a bincount?
# Assuming a bincount array 'bincount_arr'
bincount_arr = np.array([0, 1, 2, 0, 1, 3]) # Example bincount array
arr = np.repeat(np.arange(len(bincount_arr)), bincount_arr)
print(arr)

[1 2 2 4 5 5 5]


In [209]:
# 66.How do you compute a moving average using a sliding window?
from numpy.lib.stride_tricks import sliding_window_view
arr = np.arange(10)
window_size = 3
moving_avg = sliding_window_view(arr, window_size).mean(axis=-1)
print(moving_avg)

[1. 2. 3. 4. 5. 6. 7. 8.]


In [210]:
# 67.How do you create a rolling 2D view from a 1D array?
from numpy.lib.stride_tricks import sliding_window_view
arr = np.arange(10)
window_size = 3
rolling_view = sliding_window_view(arr, window_size)
print(rolling_view)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [211]:
# 68.How do you invert booleans or negate floats in-place?
bool_arr = np.array([True, False, True])
bool_arr[:] = ~bool_arr # Invert booleans in-place
print(bool_arr)

float_arr = np.array([1.5, -2.3, 0.0])
float_arr[:] = -float_arr # Negate floats in-place
print(float_arr)

[False  True False]
[-1.5  2.3 -0. ]


In [212]:
# 69.How do you compute the distance from a point to multiple lines?
# This requires defining points and lines, and using geometric formulas.
# Example: Distance from a point (x0, y0) to a line defined by two points (x1, y1) and (x2, y2)
# Formula: |(x2 - x1)(y1 - y0) - (x1 - x0)(y2 - y1)| / sqrt((x2 - x1)**2 + (y2 - y1)**2)

point = np.array([1, 1])
lines = np.array([[[0, 0], [2, 2]], [[0, 5], [5, 0]]]) # Two lines

# Vector for the line
line_vectors = lines[:, 1, :] - lines[:, 0, :]

# Vector from point to the first point of the line
point_vectors = point - lines[:, 0, :]

# Cross product for the numerator (2D equivalent)
numerator = np.abs(line_vectors[:, 0] * point_vectors[:, 1] - line_vectors[:, 1] * point_vectors[:, 0])

# Denominator (length of the line vector)
denominator = np.sqrt(np.sum(line_vectors**2, axis=1))

# Handle case where denominator is zero (line is a point)
denominator[denominator == 0] = 1e-10

distances = numerator / denominator
print(distances)

[0.         2.12132034]


In [213]:
# 70.How do you compute the distances from multiple points to multiple lines?
# This requires defining multiple points and lines, and using geometric formulas.
# Example with broadcasting

points = np.array([[1, 1], [3, 3]]) # Two points
lines = np.array([[[0, 0], [2, 2]], [[0, 5], [5, 0]]]) # Two lines

# Reshape points and lines for broadcasting
points_reshaped = points[:, np.newaxis, :] # Shape (num_points, 1, 2)
lines_reshaped = lines[np.newaxis, :, :, :] # Shape (1, num_lines, 2, 2)

# Vector for the lines
line_vectors = lines_reshaped[:, :, 1, :] - lines_reshaped[:, :, 0, :]

# Vector from points to the first point of the lines
point_vectors = points_reshaped - lines_reshaped[:, :, 0, :]

# Cross product for the numerator (2D equivalent)
numerator = np.abs(line_vectors[:, :, 0] * point_vectors[:, :, 1] - line_vectors[:, :, 1] * point_vectors[:, :, 0])

# Denominator (length of the line vector)
denominator = np.sqrt(np.sum(line_vectors**2, axis=2))

# Handle case where denominator is zero (line is a point)
denominator[denominator == 0] = 1e-10

distances = numerator / denominator
print(distances)

[[0.         2.12132034]
 [0.         0.70710678]]


In [214]:
# 71.How do you extract a fixed-shaped subarray centered on a given point?
arr = np.arange(100).reshape(10, 10)
center = (5, 5)
shape = (3, 3)

# Calculate the starting and ending indices for the subarray
start_row = center[0] - shape[0] // 2
end_row = start_row + shape[0]
start_col = center[1] - shape[1] // 2
end_col = start_col + shape[1]

# Ensure indices are within array bounds
start_row = max(0, start_row)
end_row = min(arr.shape[0], end_row)
start_col = max(0, start_col)
end_col = min(arr.shape[1], end_col)

subarray = arr[start_row:end_row, start_col:end_col]
print(subarray)

[[44 45 46]
 [54 55 56]
 [64 65 66]]


In [215]:
# 72.How do you generate overlapping subarrays from a vector?
from numpy.lib.stride_tricks import sliding_window_view
arr = np.arange(10)
window_size = 3
overlapping_subarrays = sliding_window_view(arr, window_size)
print(overlapping_subarrays)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [216]:
# 73.How do you compute the rank of a matrix using SVD?
arr = np.random.rand(5, 5)
_, s, _ = np.linalg.svd(arr)
rank = np.sum(s > 1e-10) # Check singular values against a small tolerance
print(rank)

5


In [217]:
# 74.How do you find the most frequent value in an array?
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
counts = np.bincount(arr)
most_frequent_value = np.argmax(counts)
print(most_frequent_value)

4


In [218]:
# 75.How do you extract all 3x3 contiguous blocks from a 10x10 matrix?
from numpy.lib.stride_tricks import sliding_window_view
arr = np.arange(100).reshape(10, 10)
blocks = sliding_window_view(arr, (3, 3))
print(blocks)

[[[[ 0  1  2]
   [10 11 12]
   [20 21 22]]

  [[ 1  2  3]
   [11 12 13]
   [21 22 23]]

  [[ 2  3  4]
   [12 13 14]
   [22 23 24]]

  [[ 3  4  5]
   [13 14 15]
   [23 24 25]]

  [[ 4  5  6]
   [14 15 16]
   [24 25 26]]

  [[ 5  6  7]
   [15 16 17]
   [25 26 27]]

  [[ 6  7  8]
   [16 17 18]
   [26 27 28]]

  [[ 7  8  9]
   [17 18 19]
   [27 28 29]]]


 [[[10 11 12]
   [20 21 22]
   [30 31 32]]

  [[11 12 13]
   [21 22 23]
   [31 32 33]]

  [[12 13 14]
   [22 23 24]
   [32 33 34]]

  [[13 14 15]
   [23 24 25]
   [33 34 35]]

  [[14 15 16]
   [24 25 26]
   [34 35 36]]

  [[15 16 17]
   [25 26 27]
   [35 36 37]]

  [[16 17 18]
   [26 27 28]
   [36 37 38]]

  [[17 18 19]
   [27 28 29]
   [37 38 39]]]


 [[[20 21 22]
   [30 31 32]
   [40 41 42]]

  [[21 22 23]
   [31 32 33]
   [41 42 43]]

  [[22 23 24]
   [32 33 34]
   [42 43 44]]

  [[23 24 25]
   [33 34 35]
   [43 44 45]]

  [[24 25 26]
   [34 35 36]
   [44 45 46]]

  [[25 26 27]
   [35 36 37]
   [45 46 47]]

  [[26 27 28]
   [36 37 38]


In [219]:
# 76.How do you create a 2D symmetric matrix class?
# This is a more advanced topic and requires defining a custom class that inherits from np.ndarray
# Example structure:
class SymmetricMatrix(np.ndarray):
    def __new__(cls, input_array):
        # Ensure the input is a square array
        if input_array.shape[0] != input_array.shape[1]:
            raise ValueError("Input array must be square for a symmetric matrix.")
        # Ensure the input is symmetric (within a tolerance)
        if not np.allclose(input_array, input_array.T):
             raise ValueError("Input array must be symmetric.")

        obj = np.asarray(input_array).view(cls)
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        # No additional attributes needed for this simple example

# Example Usage:
symmetric_arr = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]])
try:
    sym_matrix = SymmetricMatrix(symmetric_arr)
    print("Symmetric Matrix created successfully:")
    print(sym_matrix)

    # Example of non-symmetric matrix (will raise error)
    # non_symmetric_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    # non_sym_matrix = SymmetricMatrix(non_symmetric_arr)
except ValueError as e:
    print(f"Error creating Symmetric Matrix: {e}")

Symmetric Matrix created successfully:
[[1 2 3]
 [2 4 5]
 [3 5 6]]


In [220]:
# 77.How do you compute the sum of multiple matrix-vector products at once?
# This can be done efficiently using np.einsum.
matrices = np.random.rand(10, 5, 5) # 10 matrices of size 5x5
vectors = np.random.rand(10, 5)    # 10 vectors of size 5
result = np.einsum('ijk,ik->i', matrices, vectors)
print(result)

[8.88535959 9.02652045 3.49518467 6.99466665 7.5371351  8.1796049
 8.2950655  6.29840374 6.39458712 4.06831434]


In [221]:
# 78.How do you compute the sum of blocks in a 2D array?
# This can be done by reshaping the array and summing along the appropriate axes.
# Example: sum of 2x2 blocks in a 4x4 array
arr = np.arange(16).reshape(4, 4)
block_sum = arr.reshape(2, 2, 2, 2).sum(axis=(1, 3))
print(block_sum)

[[10 18]
 [42 50]]


In [222]:
# 79.How do you simulate the Game of Life using NumPy?
# This is a complex task involving grid updates based on neighbor rules.
# This is a simplified example and doesn't implement all Game of Life rules.
# A full implementation would require checking neighbors and applying the rules.

def update_game_of_life(grid):
    # This is a placeholder function. A real implementation
    # would calculate the next generation based on neighbor counts.
    print("Simulating Game of Life step (placeholder)...")
    return grid # Return the same grid for now

# Example initial grid
grid = np.random.randint(0, 2, (10, 10))
print("Initial Grid:")
print(grid)

# Simulate a few steps (using the placeholder function)
num_steps = 3
for _ in range(num_steps):
    grid = update_game_of_life(grid)
    # print(f"Grid after step {_ + 1}:")
    # print(grid)

print("\nSimulation complete (placeholder function used).")
print("A full Game of Life implementation requires neighbor checking and rule application.")

Initial Grid:
[[1 1 1 1 1 0 1 0 0 1]
 [0 1 0 1 0 0 1 1 1 1]
 [1 0 0 1 1 0 1 1 0 0]
 [1 1 1 1 0 0 1 1 0 0]
 [1 1 1 1 1 0 0 1 0 1]
 [0 0 0 0 0 0 0 0 1 1]
 [0 0 1 0 0 1 1 1 1 0]
 [1 1 0 0 1 0 1 1 1 1]
 [0 0 0 1 0 1 1 0 0 1]
 [1 1 1 1 0 1 0 0 1 0]]
Simulating Game of Life step (placeholder)...
Simulating Game of Life step (placeholder)...
Simulating Game of Life step (placeholder)...

Simulation complete (placeholder function used).
A full Game of Life implementation requires neighbor checking and rule application.


In [223]:
# 80.How do you extract the top N largest values from an array?
arr = np.random.rand(10)
n = 3
top_n_values = np.sort(arr)[-n:]
print(top_n_values)

[0.74391631 0.91767855 0.92577482]


In [224]:
# 81.How do you create a Cartesian product of multiple input arrays?
# This can be done using np.meshgrid or np.indices.
# Example with np.indices:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
ixgrid = np.indices((len(arr1), len(arr2)))
cartesian_product = np.c_[arr1[ixgrid[0].ravel()], arr2[ixgrid[1].ravel()]]
print(cartesian_product)

[[1 3]
 [1 4]
 [2 3]
 [2 4]]


In [225]:
# 82.How do you create a record array from a regular NumPy array?
arr = np.array([(1, 'a'), (2, 'b')], dtype=[('col1', int), ('col2', 'U1')])
# To create from a regular array, you would need to define the dtype and structure.
print(arr)

[(1, 'a') (2, 'b')]


In [226]:
# 83.How do you raise an array to the power of 3 using different methods?
arr = np.arange(5)
print(arr**3)
print(np.power(arr, 3))
print(arr * arr * arr)

[ 0  1  8 27 64]
[ 0  1  8 27 64]
[ 0  1  8 27 64]


In [227]:
# 84.How do you find rows in a matrix containing all elements of another matrix?
# This can be done by sorting rows and using np.in1d or similar logic.
# Example: find rows in matrix1 that contain all elements of matrix2
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 6], [1, 2, 3]])
matrix2 = np.array([1, 2])

# Check if each element of matrix2 is in each row of matrix1
# This approach checks if *at least one* instance of each element is present.
# For checking if ALL elements are present in a row (like a subset), a different approach might be needed
# depending on whether duplicates matter and order matters.

# Simple check if elements of matrix2 are present in rows of matrix1 (order and duplicates not considered)
rows_containing_elements = np.all([np.isin(matrix1, val).any(axis=1) for val in matrix2], axis=0)
print("Rows containing elements of matrix2:", matrix1[rows_containing_elements])

# A more robust approach if order/duplicates in the subset are important would involve sorting rows
# and then using something like np.in1d on the sorted flattened arrays, or more complex comparisons.
print("\nNote: The above checks for presence of elements, not necessarily as a subset.")
print("For strict subset checking (order/duplicates), more advanced techniques might be needed.")

Rows containing elements of matrix2: [[1 2 3]
 [1 2 6]
 [1 2 3]]

Note: The above checks for presence of elements, not necessarily as a subset.
For strict subset checking (order/duplicates), more advanced techniques might be needed.


In [228]:
# 85.How do you filter rows in a matrix with at least one differing value?
# This can be done by comparing rows and using np.any.
# Example: filter rows in matrix1 that are different from matrix2
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [7, 8, 9]])
matrix2 = np.array([1, 2, 3])

# Compare each row of matrix1 to matrix2
# The result is a boolean array indicating which elements are different
diff_elements = matrix1 != matrix2

# Use np.any along axis=1 to find rows with at least one differing element
differing_rows_mask = np.any(diff_elements, axis=1)

# Select the rows from matrix1 using the boolean mask
differing_rows = matrix1[differing_rows_mask]
print(differing_rows)

[[4 5 6]
 [7 8 9]]


In [229]:
# 86.How do you convert integers to their binary matrix representation?
# This can be done using np.unpackbits.
arr = np.array([1, 2, 3], dtype=np.uint8)
binary_matrix = np.unpackbits(arr[:, np.newaxis], axis=1)
print(binary_matrix)

[[0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]]


In [230]:
# 87.How do you extract unique rows from a 2D array?
arr = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [7, 8, 9]])
unique_rows = np.unique(arr, axis=0)
print(unique_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [231]:
# 88.How do you compute inner, outer, sum, and multiplication using einsum?
A = np.arange(25).reshape(5,5)
B = np.arange(25).reshape(5,5)

# Inner product
inner = np.einsum('i,i', A.flatten(), B.flatten())
print("Inner product:", inner)

# Outer product
outer = np.einsum('i,j', A.flatten(), B.flatten())
print("Outer product shape:", outer.shape) # Print shape as the output is large

# Sum
sum_A = np.einsum('ij->', A)
print("Sum of A:", sum_A)

# Multiplication
element_wise_mul = np.einsum('ij,ij->ij', A, B)
print("Element-wise multiplication shape:", element_wise_mul.shape) # Print shape as the output is large

Inner product: 4900
Outer product shape: (25, 25)
Sum of A: 300
Element-wise multiplication shape: (5, 5)


In [234]:
# 89.How do you sample a 2D path at regular intervals?
path = np.array([[0, 0], [1, 2], [3, 3], [6, 5]])
import numpy as np

# Example 2D path
path = np.array([[0, 0], [1, 2], [3, 3], [6, 5]])

# 1️⃣ Compute distances between consecutive points
diffs = np.diff(path, axis=0)
segment_lengths = np.hypot(diffs[:,0], diffs[:,1])

# 2️⃣ Compute cumulative distance along the path
cumdist = np.insert(np.cumsum(segment_lengths), 0, 0)

# 3️⃣ Decide regular intervals (e.g., every 0.5 units)
interval = 0.5
regular_distances = np.arange(0, cumdist[-1], interval)

# 4️⃣ Interpolate x and y coordinates at those distances
x_interp = np.interp(regular_distances, cumdist, path[:,0])
y_interp = np.interp(regular_distances, cumdist, path[:,1])

# 5️⃣ Combine into a new (N×2) array
sampled_path = np.stack((x_interp, y_interp), axis=1)

print(sampled_path)


[[0.         0.        ]
 [0.2236068  0.4472136 ]
 [0.4472136  0.89442719]
 [0.67082039 1.34164079]
 [0.89442719 1.78885438]
 [1.23606798 2.11803399]
 [1.68328157 2.34164079]
 [2.13049517 2.56524758]
 [2.57770876 2.78885438]
 [3.02318429 3.01545619]
 [3.43920943 3.29280629]
 [3.85523458 3.57015639]
 [4.27125973 3.84750649]
 [4.68728488 4.12485658]
 [5.10331002 4.40220668]
 [5.51933517 4.67955678]
 [5.93536032 4.95690688]]


In [233]:
# 90.How do you filter 2D array rows that sum to a specific number using only integers?
arr = np.array([[1, 2, 3], [4, 5, 6], [1, 1, 1], [7, 8, 9]])
target_sum = 3
filtered_rows = arr[np.sum(arr, axis=1) == target_sum]
print(filtered_rows)

[[1 1 1]]
